server:
  tomcat:
    accept-count: 1000
    max-connections: 10000
    uri-encoding: UTF-8
    threads:
      max: 800
      min-spare: 100
    connection-timeout: 5000ms
  port: 8080
  servlet:
    context-path: /common

logging:
  config: classpath:log4j2.xml

spring:
  redis:
    database: 0
#    password: #redis密码
    host: 172.21.91.114
    port: 6379
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    druid:
      url: jdbc:mysql://172.21.91.114:3306/multitenant_integrated_trade?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
      username: root
      password: 87654321
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      #validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        #login-username: admin
        #login-password: admin
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true



mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  typeAliasesPackage: com.codebaobao.model
  global-config:
    id-type: 0
    field-strategy: 1
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    cache-enabled: false
    jdbc-type-for-null: 'null'
    call-setters-on-nulls: true



